[project]
name = "amm-resume"
authors = ["AMM Resume Team"]
description = "A decentralized AMM platform for professional resume and skill verification"
telemetry = false
requirements = []

[contracts.resume-pool]
path = "contracts/resume-pool.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
